# Generated by Django 5.0.7 on 2024-07-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='W', max_length=1),
        ),
    ]
