# Generated by Django 5.0.7 on 2024-07-19 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
