# Generated by Django 5.0.7 on 2024-07-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='items',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
