# Generated by Django 5.0.7 on 2024-07-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_alter_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
