# Generated by Django 5.0.7 on 2024-07-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_comment_item_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
