# Generated by Django 5.0.7 on 2024-07-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
