# Generated by Django 5.0.7 on 2024-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_myuser_items'),
        ('item', '0002_remove_item_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='items',
        ),
        migrations.AddField(
            model_name='myuser',
            name='items',
            field=models.ManyToManyField(null=True, related_name='users', to='item.item'),
        ),
    ]
