# Generated by Django 5.0.7 on 2024-07-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_myuser_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
